# Generated by Django 6.0.6 on 2026-07-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Accessory', 'Accessory'), ('Gadgets', 'Gadgets'), ('Audio', 'Audio')], default='Mobile', max_length=20),
        ),
    ]
